### ISSUE TITLE
the version of tensorflow

### ISSUE THREAD

**Issue by fujisatoshi** [yvestegnya2/deep-autoencoders-cartography#3]
Hi！I installed tensorflow1.14+python3.6 to run this experiment，but there is a mistake“ (0) Internal: Blas xGEMMBatched launch failed : ”Could you please tell me the detail version of the package tensorflow so I can run this experiment successful.

**Comment by fachu000** [comment]
Sorry, I just saw the issue.

**Comment by fujisatoshi** [comment]
Hi,now i can run this experiment partly,but the result are not good,and my gpu always run out of memory cause the process suddenly killed,can I know what GPU and CPU this experiment was run on before?Thanks.

**Comment by fachu000** [comment]
I do not remember the exact hardware. You may try reducing the batch size.
If that doesn't work, you may check with a small dataset. But it should
work.
